# Docker compose file helping with running the test suite
# Meant to be run by Docker Cloud Autotest facility

version: "3.5"
services:

  sut:
    build: 
      context: .
      dockerfile: Dockerfile-test
    net: host
    volumes:
      - ./:/src
    working_dir: /src
    privileged: true
    environment:
      IMAGE_NAME: this
    command: pytest -v
