# Docker compose file helping with running the test suite
# Meant to be run by Docker Cloud Autotest facility

version: "3.5"
services:

  sut:
    build: 
      context: tests
      dockerfile: Dockerfile-tests
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:${PWD}:ro
    working_dir: ${PWD}
    privileged: true
    environment:
      IMAGE_NAME: ${IMAGE_NAME}  # in Docker Cloud Autotest, ``IMAGE_NAME`` is the name given to the built docker image
    command: pytest -v
