version: "3.5"
services:

  sut:
    build: 
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./:/src
    working_dir: /src
    privileged: true
    environment:
      IMAGE_NAME=this
    command: pytest -v
