# Docker file used to build a Docker image having all dependencies required
# to run the test suite.

FROM docker:stable
RUN apk --no-cache add git python py-pip
RUN pip install docker-compose
COPY ./requirements.txt /
RUN pip install -r /requirements.txt
