# Docker file used to build a Docker image having all dependencies required
# to run the test suite.

FROM docker:stable
RUN apk --no-cache add git python3 py3-pip
RUN pip3 install docker-compose
COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt
