#!/bin/bash
set -eu

# $IMAGE_NAME var is injected into the build so the tag is correct.

cat <<EOT

===============================================================================

BUILD

===============================================================================

EOT

docker pull tomdesinto/jenkins-dsl-ready:latest || true
docker build \
  --pull \
  --cache-from=tomdesinto/jenkins-dsl-ready:latest \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  -t $IMAGE_NAME .
